theme = "gruvbox-material"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
true-color = true
completion-trigger-len = 1
completion-timeout = 2

trim-trailing-whitespace = true

rulers = [80]

auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
auto-signature-help = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[keys.insert]
"esc" = [":sh macism com.apple.keylayout.ABC", "normal_mode"]

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "â”‚"
